### ISSUE TITLE
Thanks you for your great code.

### ISSUE THREAD

**Issue by bemoregt** [haydengunraj/Phase-Shift-Transform-CPP#1]
Hi, @haydengunraj 

Thanks you for your great code.

I have made an openframeworks verison with your code.
https://github.com/bemoregt/ofxPhaseStretchF.git 

Is that all right?

Best,
@bemoregt.

**Comment by haydengunraj** [comment]
Hi @bemoregt ,

You're free to use the code as you please! I see that you've already included the copyright notice from the [original Matlab implementation](https://github.com/JalaliLabUCLA/Image-feature-detection-using-Phase-Stretch-Transform), but it may also be worth adding a link to the repo in your references section.

Cheers,
@haydengunraj
